apiVersion: v1
kind: Pod
metadata:
   name: isoltest-app-a
spec:
   containers:
      - name: app-a
        image: kshino/appa
        ports:
           -  containerPort: 5001
---
apiVersion: v1
kind: Pod
metadata:
   name: isoltest-app-b
spec:
   containers:
      - name: app-b
        image: kshino/appb
        ports:
           -  containerPort: 5001
---
apiVersion: v1
kind: Pod
metadata:
   name: isoltest-app-c1
spec:
   containers:
      - name: app-c
        image: kshino/appc
        ports:
           -  containerPort: 5001
---
apiVersion: v1
kind: Pod
metadata:
   name: isoltest-app-c2
spec:
   containers:
      - name: app-c
        image: kshino/appc
        ports:
           -  containerPort: 5001
