apiVersion: v1
kind: Pod
metadata:
   name: isoltest-app-a
   labels:
      app: app-a
spec:
   containers:
      - name: app-a
        image: kshino/appa
        ports:
           -  containerPort: 5201
---
apiVersion: v1
kind: Pod
metadata:
   name: isoltest-app-b
   labels:
      app: app-b
spec:
   containers:
      - name: app-b
        image: kshino/appb
        ports:
           -  containerPort: 5201
---
apiVersion: v1
kind: Pod
metadata:
   name: isoltest-app-c1
   labels:
      app: app-c1
spec:
   containers:
      - name: app-c
        image: kshino/appc
        ports:
           -  containerPort: 5201
---
apiVersion: v1
kind: Pod
metadata:
   name: isoltest-app-c2
   labels:
      app: app-c2
spec:
   containers:
      - name: app-c
        image: kshino/appc
        ports:
           -  containerPort: 5201
---
apiVersion: v1
kind: Pod
metadata:
   name: isoltest-esearch
   labels:
      app: esearch
spec:
   containers:
      - name: esearch
        image: kshino/elasticsearch
        ports:
           -  containerPort: 5201
---
apiVersion: v1
kind: Pod
metadata:
   name: isoltest-fluentd
   labels:
      app: fluentd
spec:
   containers:
      - name: fluentd
        image: kshino/fluentd
        ports:
           -  containerPort: 5201
---
apiVersion: v1
kind: Service
metadata:
   name: svc-app-a
spec:
   selector:
      app: app-a
   ports:
   - protocol: TCP
     port: 5201
     targetPort: 5201
---
apiVersion: v1
kind: Service
metadata:
   name: svc-app-b
spec:
   selector:
      app: app-b
   ports:
   - protocol: TCP
     port: 5201
     targetPort: 5201
---
apiVersion: v1
kind: Service
metadata:
   name: svc-app-c1
spec:
   selector:
      app: app-c1
   ports:
   - protocol: TCP
     port: 5201
     targetPort: 5201
---
apiVersion: v1
kind: Service
metadata:
   name: svc-app-c2
spec:
   selector:
      app: app-c2
   ports:
   - protocol: TCP
     port: 5201
     targetPort: 5201

