apiVersion: v1
kind: Pod
metadata:
   name: isoltest-app-a
   labels:
      app: app-a
spec:
   containers:
      - name: app-a
        image: localhost:5000/appa
        ports:
           -  containerPort: 5201
---
#apiVersion: v1
#kind: Pod
#metadata:
#   name: isoltest-app-b
#   labels:
#      app: app-b
#spec:
#   containers:
#      - name: app-b
#        image: localhost:5000/appb
#        ports:
#           -  containerPort: 5201
---
apiVersion: v1
kind: Pod
metadata:
   name: isoltest-app-c1
   labels:
      app: app-c1
spec:
   containers:
      - name: app-c
        image: localhost:5000/appc
        ports:
           -  containerPort: 5201
---
#apiVersion: v1
#kind: Pod
#metadata:
#   name: isoltest-app-c2
#   labels:
#      app: app-c2
#spec:
#   containers:
#      - name: app-c
#        image: localhost:5000/appc
#        ports:
#           -  containerPort: 5201
---
apiVersion: v1
kind: Pod
metadata:
   name: isoltest-esearch
   labels:
      app: esearch
      srv: kibana
      graph: grafana
spec:
   containers:
      - name: esearch
        image: localhost:5000/elasticsearch
        ports:
           -  containerPort: 9200
      - name: kibana
        image: localhost:5000/kibana
        ports:
           -  containerPort: 5601
      - name: grafana
        image: localhost:5000/grafana
        ports:
           -  containerPort: 3000
---
apiVersion: v1
kind: Pod
metadata:
   name: isoltest-sense
   labels:
      app: sense
spec:
   containers:
      - name: sense
        image: s12v/sense
        ports:
           -  containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
   name: svc-app-a
spec:
   selector:
      app: app-a
   ports:
   - protocol: TCP
     port: 5201
     targetPort: 5201
---
apiVersion: v1
kind: Service
metadata:
   name: svc-app-b
spec:
   selector:
      app: app-b
   ports:
   - protocol: TCP
     port: 5201
     targetPort: 5201
---
apiVersion: v1
kind: Service
metadata:
   name: svc-app-c1
spec:
   selector:
      app: app-c1
   ports:
   - protocol: TCP
     port: 5201
     targetPort: 5201
---
apiVersion: v1
kind: Service
metadata:
   name: svc-app-c2
spec:
   selector:
      app: app-c2
   ports:
   - protocol: TCP
     port: 5201
     targetPort: 5201

---
apiVersion: v1
kind: Service
metadata:
   name: svc-esearch
spec:
   selector:
      app: esearch
   type: LoadBalancer
   ports:
   - protocol: TCP
     port: 9200
     targetPort: 9200
---
apiVersion: v1
kind: Service
metadata:
   name: svc-kibana
spec:
   selector:
      srv: kibana
   type: LoadBalancer
   ports:
   - protocol: TCP
     port: 5601
     targetPort: 5601
---
apiVersion: v1
kind: Service
metadata:
   name: svc-grafana
spec:
   selector:
      graph: grafana
   type: LoadBalancer
   ports:
   - protocol: TCP
     port: 3000
     targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
   name: svc-sense
spec:
   selector:
      app: sense 
   type: LoadBalancer
   ports:
   - protocol: TCP
     port: 5602
     targetPort: 5601

